### ISSUE TITLE
ArgumentException at Exercise 4 Task 2

### ISSUE THREAD

**Issue by runceel** [Microsoft/AppConsult-WinAppsModernizationWorkshop#45]
I watch following error on the Output Window.

```
System.Windows.Data Error: 8 : Cannot save value from target back to source. BindingExpression:Path=Date; DataItem='AddNewExpenseViewModel' (HashCode=18970462); target element is 'CalendarViewWrapper' (Name=''); target property is 'SelectedDate' (type 'DateTimeOffset') ArgumentException:'System.ArgumentException: Object of type 'System.DateTimeOffset' cannot be converted to type 'System.DateTime'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at MS.Internal.Data.PropertyPathWorker.SetValue(Object item, Object value)
   at System.Windows.Data.BindingExpression.UpdateSource(Object value)'
```

The cause of this error is type missmatch between SelectedDate property of CalendarViewWrapper to Date property of AddNewExpenseViewModel.

CalendarViewWrapper one is DateTimeOffset. AddNewExpenseViewModel one is DateTime.

After change the property type of AddNewExpenseViewModel.Date and Expense.Date the error was fixed.(In fact, the End folder of Exercise 4 is changed to DateTimeOffset.)

I think that adding this step at step 6 of Exercise 4 Task 2 is good for fixing the issue.

**Comment by qmatteoq** [comment]
Fixed in a9a2c21
